In [24]:
import random
import pandas as pd
from IPython.display import display
from sklearn.utils import shuffle

In [71]:
hu = pd.read_csv("Hu.csv", )
lu = pd.read_csv("Lu.csv")
hu.drop(['序号'], axis = 1, inplace = True), lu.drop(['序号'], axis = 1, inplace = True)
hu['导师'] = '胡'
lu['导师'] = '陆'
display(hu.head(), lu.head())

    姓名 性别 导师
0   李帅  男  胡
1   梁晨  女  胡
2   郭慧  女  胡
3  徐嘉晨  女  胡
4  时吉星  男  胡

    姓名 性别 导师
0  薄新月  女  陆
1  黄加玮  男  陆
2  罗颖科  女  陆
3  刘宇晴  女  陆
4  邵晓旭  女  陆

In [296]:
total = shuffle(pd.concat([hu, lu], ignore_index=True))

In [229]:
total["性别"].value_counts()

女    40
男    29
Name: 性别, dtype: int64

In [313]:
total["导师"][:5].value_counts()['陆']

1

In [314]:
def shuffle_list(names):
    first = [x for x in range(0, 70, 5)]
    state = 0
    while state == 0:
        names = shuffle(names)
        names.index = range(len(names))
        for i in first:
            if len(list(names["性别"][i:i + 5].value_counts())) < 2:
                state += 1
            elif len(list(names["导师"][i:i + 5].value_counts())) < 2 or names["导师"][i:i + 5].value_counts()['陆'] > 2:
                state += 1
        if state == 0:
            return names
        else:
            state = 0
        

result = shuffle_list(total)

In [339]:
a = [x for x in range(1, 15)]
result.index = list(map(str, sum(list(map(list,zip(a, a, a, a, a))), [])[:-1]))
display(result[:25])
display(result[25:50])
display(result[50:])

    姓名 性别 导师
1  罗颖科  女  陆
1  郑泽先  男  胡
1  李梦珂  女  胡
1  潘海燕  女  陆
1  庞范烨  女  胡
2  李伟哲  男  胡
2  刘钊明  男  胡
2  黄新婷  女  胡
2   郭慧  女  胡
2  刘方博  男  陆
3  文杏容  女  陆
3  晋漪萌  女  胡
3   戴劭  女  胡
3   李帅  男  胡
3  薄新月  女  陆
4   朱磊  男  胡
4  梁连英  女  胡
4  时吉星  男  胡
4   张龙  男  胡
4  刘宇晴  女  陆
5   李曈  女  胡
5  黄加玮  男  陆
5  李顽强  男  胡
5  钟海静  女  胡
5  黄嘉敏  女  胡

     姓名 性别 导师
6    陈帅  男  胡
6    席悦  女  胡
6    姜雪  女  胡
6   曹静芸  女  胡
6   温一锋  男  陆
7    钱程  男  胡
7    谢沛  男  胡
7   王泓娇  女  陆
7   姚小玉  女  胡
7   唐倩楠  女  胡
8   刘典财  男  胡
8    梁晨  女  胡
8   徐嘉晨  女  胡
8    苏亚  男  陆
8   冯梓昱  男  胡
9   袁方铭  男  胡
9    陈梦  女  胡
9   季焕钦  男  胡
9   吴培思  女  陆
9   曹在笑  男  胡
10   宋姗  女  胡
10  覃连鲜  女  胡
10   陈坤  男  陆
10   张慧  女  胡
10   杜嵩  男  胡

     姓名 性别 导师
11   王宁  男  胡
11  潘艺文  女  陆
11  陈志坤  男  胡
11  邵晓旭  女  陆
11   彭凌  女  胡
12  王嘉丹  女  陆
12  康梦霞  女  胡
12  余诗燕  女  陆
12  林颖琛  男  胡
12  赖敏瑜  女  胡
13   邸玥  女  胡
13  陈翰飞  男  胡
13  赵雨淋  女  陆
13  龚敏琪  女  胡
13  叶震宽  男  胡
14  张志勇  男  陆
14  陈义鹏  男  胡
14   卜丹  女  胡
14  李敏敏  女  胡

In [342]:
result.to_excel("result.xlsx", encoding='utf-8', index_label='组别')